name: Test action
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    container: 
      image: orgflow/cli:1.x
      env:
        ORGFLOW_ACCEPTEULA: true

    steps:
      - uses: orgflow-actions/set-salesforce-auth@dev
        id: set-auth
        with:
          stack-name: Main
          username: ${{ secrets.SALESFORCE_USERNAME }}
          password: ${{ secrets.SALESFORCE_PASSWORD }}
          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}
      - run: echo ${{ steps.set-auth.outputs.encryption-key }}
